### ISSUE TITLE
Audio test issues

### ISSUE THREAD

**Issue by viciious** [Dasutin/32X240pTestSuite#13]
1) enabling all 4 PSG channels in the sound test menu and leaving the menu doesn't disable them
2) re-entering the audio test menu afterwards adds a horrible squeaking noise on top of all 4 PSG channels, probably coming from 32X's PWM

**Comment by Dasutin** [comment]
Fixed. Forgot to stop the PSG when leaving the test. Also reduced the amount of time each PSG channel is active when testing.
